name: facerd_flutter
description: "Flutter plugin for integrating with FaceRD Registered Device face capture."
version: 0.0.1
repository: https://github.com/ravi84184/facerd_flutter

environment:
  sdk: ^3.10.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:

  plugin:
    platforms:
      android:
        package: com.example.facerd_flutter
        pluginClass: FacerdFlutterPlugin
      ios:
        pluginClass: FacerdFlutterPlugin
